name: Sync To AtomGit
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
jobs:  
  sync:
    runs-on: ubuntu-latest
    environment: 'atomgit-config'
    steps:
      - uses: actions/checkout@v4



      - name: Push
        env: 
          ATOMGITTOKEN: ${{ secrets.ATOMGITTOKEN }}
          ATOMGITUSER: ${{ secrets.ATOMGITUSER }}
        run: |

          python3 sync.py ${{ secrets.ATOMGITUSER }} ${{ secrets.ATOMGITTOKEN }}
