name: Sync To AtomGit
on: 
  push:
    branches: [ master ]

jobs:  
  sync:
    runs-on: ubuntu-latest
    environment: 'atomgit config'  # 必须与你创建的环境名称完全一致
    steps:
      - uses: actions/checkout@v4

      - name: Push to AtomGit
        run: python3 sync.py ${{ secrets.ATOMGITUSER }} ${{ secrets.ATOMGITTOKEN }}
